### PR TITLE
Add Venue resource

### PR DESCRIPTION
**Pull request by Drakula2k**

### CODE REVIEW

**Comment by sssionggg** [comment]
@Drakula2k i was playing with this API, it doesn't seem to work.  I keep getting `404` error.

**Comment by Drakula2k** [comment]
@siong1987 You can get valid venue_id on any event details.

**Comment by kamal** [comment]
@Drakula2k thanks!

**Comment by troycroz** [comment]
Can you update the gem in rubygems? It seems this PR and other more recent ones haven't made it there yet:
https://rubygems.org/gems/eventbrite

Took me a while to figure out why Eventbrite::Venue was unfound. For now, have to do this:
`gem 'eventbrite', :git => 'https://github.com/envoy/eventbrite.git', :branch => 'master'`

**Comment by sssionggg** [comment]
@troycroz i don't longer have publish right to rubygems for this gem.  i will let @kamal handle it.

**Pull request merged**
